# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://zachdietz1.github.io/
baseurl: /home/
title: Zach Dietz
author: Zach Dietz
description: Personal Website
avatar: profile.png
email: zachdietz1@gmail.com
github: zachdietz1
twitter:
linkedin: zachary-dietz-bb936a133
stackoverflow:
# disqus: 
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
